'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const QRCode = require('qrcode');

const Util = require('./Util');
const ServerError = require('./ServerError');

const {
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_CONFIG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_DEFAULT_ADDRESS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ALLOWED_IPS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
} = require('../config');

module.exports = class WireGuard {

  constructor() {
    // Runtime-mutable server settings (seeded from env vars)
    this.__serverSettings = {
      host: WG_HOST,
      port: WG_PORT,
      configPort: WG_CONFIG_PORT,
      device: process.env.WG_DEVICE || 'eth0',
      defaultDns: WG_DEFAULT_DNS,
      defaultAddress: WG_DEFAULT_ADDRESS,
      mtu: WG_MTU,
      allowedIps: WG_ALLOWED_IPS,
      persistentKeepalive: WG_PERSISTENT_KEEPALIVE,
    };
    this.__config = null;
    this.__initPromise = null;
  }

  async __buildConfig() {
    if (this.__config) return this.__config;

    if (!this.__serverSettings.host) {
      throw new Error('WG_HOST Environment Variable Not Set!');
    }

    debug('Loading configuration...');
    let config;
    try {
      config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
      config = JSON.parse(config);
      debug('Configuration loaded.');
    } catch (err) {
      const privateKey = await Util.exec('wg genkey');
      const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
        log: 'echo ***hidden*** | wg pubkey',
      });
      const address = this.__serverSettings.defaultAddress.replace('x', '1');

      config = {
        server: {
          privateKey,
          publicKey,
          address,
        },
        clients: {},
      };
      debug('Configuration generated.');
    }

    // Ensure all clients have portForwards array
    for (const client of Object.values(config.clients)) {
      if (!Array.isArray(client.portForwards)) {
        client.portForwards = [];
      }
    }

    // Load persisted server settings if available
    try {
      const settingsRaw = await fs.readFile(path.join(WG_PATH, 'server-settings.json'), 'utf8');
      const saved = JSON.parse(settingsRaw);
      // Merge saved settings over env defaults
      Object.assign(this.__serverSettings, saved);
      debug('Server settings loaded from disk.');
    } catch {
      // No saved settings, use env defaults
    }

    this.__config = config;
    return config;
  }

  async getConfig() {
    if (!this.__config) {
      await this.__buildConfig();
    }
    return this.__config;
  }

  async init() {
    if (this.__initPromise) return this.__initPromise;

    this.__initPromise = (async () => {
      const config = await this.getConfig();

      await this.__saveConfig(config);
      await Util.exec('wg-quick down wg0').catch(() => {});
      await Util.exec('wg-quick up wg0').catch((err) => {
        if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
          throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
        }
        throw err;
      });

      await this.__syncConfig();
      await this.__ensureNftablesSetup();
      await this.__applyAllDnatRules();
      
      debug('WireGuard initialization completed.');
    })();

    return this.__initPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    await this.__saveConfig(config);
    await this.__syncConfig();
  }

  async __saveConfig(config) {
    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = ${this.__serverSettings.port}
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
`;

    for (const [clientId, client] of Object.entries(config.clients)) {
      if (!client.enabled) continue;

      result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
    }

    debug('Config saving...');
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await Util.exec('wg syncconf wg0 <(wg-quick strip wg0)');
    debug('Config synced.');
  }

  async getClients() {
    if (process.platform !== 'linux') {
      return [{
        id: 'dummy-client-preview',
        name: 'Preview Client (Local)',
        address: '10.8.0.2',
        enabled: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        transferRx: 1024 * 1024 * 500,
        transferTx: 1024 * 1024 * 120,
        portForwards: [
          { proto: 'tcp', extPort: 8080, intPort: 80 },
          { proto: 'udp', extPort: 27015, intPort: 27015 }
        ]
      }];
    }

    const config = await this.getConfig();
    const clients = Object.entries(config.clients).map(([clientId, client]) => ({
      id: clientId,
      name: client.name,
      enabled: client.enabled,
      address: client.address,
      publicKey: client.publicKey,
      createdAt: new Date(client.createdAt),
      updatedAt: new Date(client.updatedAt),
      allowedIPs: client.allowedIPs,
      portForwards: Array.isArray(client.portForwards) ? client.portForwards : [],
      downloadableConfig: 'privateKey' in client,
      persistentKeepalive: null,
      latestHandshakeAt: null,
      transferRx: null,
      transferTx: null,
    }));

    // Loop WireGuard status
    const dump = await Util.exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint, // eslint-disable-line no-unused-vars
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const client = clients.find((client) => client.publicKey === publicKey);
        if (!client) return;

        client.latestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));
        client.transferRx = Number(transferRx);
        client.transferTx = Number(transferTx);
        client.persistentKeepalive = persistentKeepalive;
      });

    return clients;
  }

  async getClient({ clientId }) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) {
      throw new ServerError(`Client Not Found: ${clientId}`, 404);
    }

    return client;
  }

  async getClientConfiguration({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getClient({ clientId });

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}/24
${this.__serverSettings.defaultDns ? `DNS = ${this.__serverSettings.defaultDns}\n` : ''}\
${this.__serverSettings.mtu ? `MTU = ${this.__serverSettings.mtu}\n` : ''}\

[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${this.__serverSettings.allowedIps}
PersistentKeepalive = ${this.__serverSettings.persistentKeepalive}
Endpoint = ${this.__serverSettings.host}:${this.__serverSettings.configPort}`;
  }

  async getClientQRCodeSVG({ clientId }) {
    const config = await this.getClientConfiguration({ clientId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  async createClient({ name }) {
    if (!name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();

    const privateKey = await Util.exec('wg genkey');
    const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
      log: 'echo ***hidden*** | wg pubkey',
    });
    const preSharedKey = await Util.exec('wg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const client = Object.values(config.clients).find((client) => {
        return client.address === this.__serverSettings.defaultAddress.replace('x', i);
      });

      if (!client) {
        address = this.__serverSettings.defaultAddress.replace('x', i);
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of clients reached.');
    }

    // Create Client
    const id = crypto.randomUUID();
    const client = {
      id,
      name,
      address,
      privateKey,
      publicKey,
      preSharedKey,

      createdAt: new Date(),
      updatedAt: new Date(),

      enabled: true,
      portForwards: [],
    };

    config.clients[id] = client;

    await this.saveConfig();

    return client;
  }

  async deleteClient({ clientId }) {
    const config = await this.getConfig();

    if (config.clients[clientId]) {
      // Clean up DNAT rules for this client before deleting
      delete config.clients[clientId];
      await this.saveConfig();
      await this.__applyAllDnatRules();
    }
  }

  async enableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = true;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async disableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = false;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientName({ clientId, name }) {
    const client = await this.getClient({ clientId });

    client.name = name;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientAddress({ clientId, address }) {
    const client = await this.getClient({ clientId });

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    client.address = address;
    client.updatedAt = new Date();

    await this.saveConfig();
    // Re-apply DNAT since IP changed
    await this.__applyAllDnatRules();
  }

  async __reloadConfig() {
    await this.__buildConfig();
    await this.__syncConfig();
  }

  async restoreConfiguration(config) {
    debug('Starting configuration restore process.');
    const _config = JSON.parse(config);

    // Ensure all clients have portForwards
    for (const client of Object.values(_config.clients || {})) {
      if (!Array.isArray(client.portForwards)) {
        client.portForwards = [];
      }
    }

    await this.__saveConfig(_config);
    await this.__reloadConfig();
    await this.__applyAllDnatRules();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('wg-quick down wg0').catch(() => {});
  }

  // ── Server Settings (Global IP Config) ──────────────────────────

  async getServerConfig() {
    // Ensure config is loaded (which also loads settings)
    await this.getConfig();
    return { ...this.__serverSettings };
  }

  async updateServerConfig(settings) {
    await this.getConfig();

    const allowed = ['host', 'port', 'configPort', 'device', 'defaultDns',
      'defaultAddress', 'mtu', 'allowedIps', 'persistentKeepalive'];

    for (const key of allowed) {
      if (settings[key] !== undefined) {
        this.__serverSettings[key] = settings[key];
      }
    }

    // Persist to disk
    await fs.writeFile(
      path.join(WG_PATH, 'server-settings.json'),
      JSON.stringify(this.__serverSettings, null, 2),
      { mode: 0o660 },
    );

    debug('Server settings updated and persisted.');
    return { ...this.__serverSettings };
  }

  // ── NFTables / DNAT ─────────────────────────────────────────────

  async __ensureNftablesSetup() {
    try {
      await Util.exec('nft add table ip wgeasy_dnat');
      await Util.exec('nft add chain ip wgeasy_dnat prerouting { type nat hook prerouting priority dstnat; policy accept; }');
      debug('nftables table/chain ensured.');
    } catch (err) {
      // It might already exist, which is fine
    }
  }

  async __applyAllDnatRules() {
    // Flush existing rules
    await Util.exec('nft flush chain ip wgeasy_dnat prerouting').catch(() => {});

    // Use config directly
    const config = await this.getConfig();
    for (const client of Object.values(config.clients)) {
      if (!client.enabled || !client.portForwards || !client.portForwards.length) continue;
      
      const peerIP = client.address.split('/')[0];
      for (const rule of client.portForwards) {
        const { proto, extPort, intPort } = rule;
        const cmd = `nft add rule ip wgeasy_dnat prerouting ${proto} dport ${extPort} dnat to ${peerIP}:${intPort}`;
        await Util.exec(cmd).catch((err) => debug(`Error applying DNAT rule: ${err.message}`));
      }
    }
    debug('All DNAT rules applied.');
  }

  async addPortForward(clientId, proto, extPort, intPort) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) throw new ServerError('Client not found', 404);

    if (!Array.isArray(client.portForwards)) client.portForwards = [];

    // Validate extPort not already used by another peer
    const conflict = Object.values(config.clients).some(c =>
      c.id !== clientId &&
      Array.isArray(c.portForwards) &&
      c.portForwards.some(r => r.proto === proto && r.extPort === extPort)
    );
    if (conflict) throw new ServerError(`Puerto ${proto}/${extPort} ya está asignado a otro peer`, 400);

    // Block the WireGuard port
    if (extPort === Number(this.__serverSettings.port)) {
      throw new ServerError(`El puerto ${this.__serverSettings.port} está reservado para WireGuard`, 400);
    }

    client.portForwards.push({ proto, extPort: Number(extPort), intPort: Number(intPort) });
    await this.saveConfig();
    await this.__applyAllDnatRules();
  }

  async removePortForward(clientId, index) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) throw new ServerError('Client not found', 404);

    if (Array.isArray(client.portForwards) && client.portForwards.length > index) {
      client.portForwards.splice(index, 1);
      await this.saveConfig();
      await this.__applyAllDnatRules();
    }
  }

  async updatePortForward(clientId, index, proto, extPort, intPort) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) throw new ServerError('Client not found', 404);

    if (!Array.isArray(client.portForwards) || client.portForwards.length <= index) {
      throw new ServerError('Port forward rule not found', 404);
    }

    // Validate extPort not already used by another peer, ignoring current rule
    const conflict = Object.values(config.clients).some(c => {
      if (!Array.isArray(c.portForwards)) return false;
      return c.portForwards.some((r, i) => {
        // If same client and same rule index, skip
        if (c.id === clientId && i === Number(index)) return false;
        return r.proto === proto && r.extPort === extPort;
      });
    });
    if (conflict) throw new ServerError(`Puerto ${proto}/${extPort} ya está asignado a otro peer`, 400);

    // Block the WireGuard port
    if (extPort === Number(this.__serverSettings.port)) {
      throw new ServerError(`El puerto ${this.__serverSettings.port} está reservado para WireGuard`, 400);
    }

    client.portForwards[index] = { proto, extPort: Number(extPort), intPort: Number(intPort) };
    await this.saveConfig();
    await this.__applyAllDnatRules();
  }

};
