services:
  wg-easy-port-manager:
    build:
      dockerfile: ./Dockerfile
    command: npm run serve-dev
    volumes:
      - ./src/:/app/
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - PASSWORD_HASH=${PASSWORD_HASH:?Set PASSWORD_HASH in .env}
      - SESSION_SECRET=${SESSION_SECRET:?Set SESSION_SECRET in .env}
      - WG_HOST=192.168.1.233
      - WG_MTU=1420
      - WG_NFT_MASQUERADE=true
      - WG_SEED_TUNING=true
