name: Build Pull Request

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  deploy:
    name: Validate Docker build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ydtoloza'
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Build Docker Image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
        tags: wg-easy-port-manager:pr
        cache-from: type=gha
        cache-to: type=gha,mode=max
